package web

import (
	"bytes"
	"fmt"
	"net/http"
	"sort"
	"strconv"
	"strings"
)

// serveMetrics writes the Prometheus text exposition format (version 0.0.4).
// It is generated by hand to keep the binary free of dependencies.
func serveMetrics(w http.ResponseWriter, opts Options) {
	snap := opts.Snapshot()
	var m metricsWriter

	m.family("ddns_updater_info", "gauge", "Build and configuration information.")
	m.sample("ddns_updater_info", 1, "version", opts.Info.Version, "provider", opts.Info.Provider)

	m.family("ddns_updater_start_time_seconds", "gauge", "Start time of the process since unix epoch in seconds.")
	m.sample("ddns_updater_start_time_seconds", unix(opts.Info.Started))

	m.family("ddns_updater_last_check_timestamp_seconds", "gauge", "Time the last check cycle completed (0 before the first cycle).")
	m.sample("ddns_updater_last_check_timestamp_seconds", unix(snap.LastCheck))

	m.family("ddns_updater_ready", "gauge", "Whether the last check cycle fully succeeded (1) or not (0).")
	m.sample("ddns_updater_ready", boolValue(opts.Health.Ready() == nil))

	m.family("ddns_updater_ip_detection_success", "gauge", "Whether the last public IP detection for the family succeeded.")
	for _, f := range snap.Families {
		m.sample("ddns_updater_ip_detection_success", boolValue(f.Error == "" && f.Address != ""), "family", f.Family)
	}
	m.family("ddns_updater_ip_detections_total", "counter", "Public IP detections by result.")
	for _, f := range snap.Families {
		m.sample("ddns_updater_ip_detections_total", float64(f.Detections), "family", f.Family, "result", "success")
		m.sample("ddns_updater_ip_detections_total", float64(f.Failures), "family", f.Family, "result", "failure")
	}
	m.family("ddns_updater_ip_changes_total", "counter", "Detected public IP address changes.")
	for _, f := range snap.Families {
		m.sample("ddns_updater_ip_changes_total", float64(f.Changes), "family", f.Family)
	}

	m.family("ddns_updater_host_in_sync", "gauge", "Whether the hostname's DNS record matches the detected public IP.")
	for _, h := range snap.Hosts {
		m.sample("ddns_updater_host_in_sync", boolValue(h.InSync), "hostname", h.Hostname)
	}
	m.family("ddns_updater_host_consecutive_failures", "gauge", "Consecutive failed updates for the hostname.")
	for _, h := range snap.Hosts {
		m.sample("ddns_updater_host_consecutive_failures", float64(h.Failures), "hostname", h.Hostname)
	}
	m.family("ddns_updater_host_dns_warning", "gauge", "Whether DNS lookups for the hostname returned only non-public addresses (split-horizon DNS).")
	for _, h := range snap.Hosts {
		m.sample("ddns_updater_host_dns_warning", boolValue(h.DNSWarning != ""), "hostname", h.Hostname)
	}
	m.family("ddns_updater_updates_total", "counter", "Provider update requests by result.")
	for _, h := range snap.Hosts {
		m.sample("ddns_updater_updates_total", float64(h.UpdatesOK), "hostname", h.Hostname, "result", "success")
		m.sample("ddns_updater_updates_total", float64(h.UpdatesFail), "hostname", h.Hostname, "result", "failure")
	}
	m.family("ddns_updater_last_update_timestamp_seconds", "gauge", "Time of the last successful update of the hostname (0 if none).")
	for _, h := range snap.Hosts {
		m.sample("ddns_updater_last_update_timestamp_seconds", unix(h.LastUpdate), "hostname", h.Hostname)
	}

	w.Header().Set("Content-Type", "text/plain; version=0.0.4; charset=utf-8")
	_, _ = w.Write(m.buf.Bytes())
}

type metricsWriter struct{ buf bytes.Buffer }

func (m *metricsWriter) family(name, typ, help string) {
	fmt.Fprintf(&m.buf, "# HELP %s %s\n# TYPE %s %s\n", name, help, name, typ)
}

// sample writes one sample; labels are name/value pairs.
func (m *metricsWriter) sample(name string, value float64, labels ...string) {
	m.buf.WriteString(name)
	if len(labels) > 0 {
		pairs := make([]string, 0, len(labels)/2)
		for i := 0; i+1 < len(labels); i += 2 {
			pairs = append(pairs, labels[i]+`="`+escapeLabel(labels[i+1])+`"`)
		}
		sort.Strings(pairs)
		m.buf.WriteString("{" + strings.Join(pairs, ",") + "}")
	}
	m.buf.WriteString(" " + strconv.FormatFloat(value, 'f', -1, 64) + "\n")
}

var labelEscaper = strings.NewReplacer(`\`, `\\`, `"`, `\"`, "\n", `\n`)

func escapeLabel(v string) string { return labelEscaper.Replace(v) }

func boolValue(b bool) float64 {
	if b {
		return 1
	}
	return 0
}
