{{- if eq (include "ddns-updater.credentialsSource" .) "external" }}
{{- with .Values.externalSecret }}
apiVersion: {{ .apiVersion }}
kind: ExternalSecret
metadata:
  name: {{ include "ddns-updater.fullname" $ }}
  labels:
    {{- include "ddns-updater.labels" $ | nindent 4 }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  refreshInterval: {{ .refreshInterval | quote }}
  secretStoreRef:
    kind: {{ .secretStoreRef.kind }}
    name: {{ .secretStoreRef.name }}
  target:
    name: {{ include "ddns-updater.secretName" $ }}
    creationPolicy: Owner
  data:
    {{- range $name, $ref := dict "username" .username "password" .password }}
    - secretKey: {{ get $.Values.credentials (printf "%sKey" $name) }}
      remoteRef:
        key: {{ $ref.key | quote }}
        {{- with $ref.property }}
        property: {{ . | quote }}
        {{- end }}
        {{- with $ref.version }}
        version: {{ . | quote }}
        {{- end }}
    {{- end }}
{{- end }}
{{- end }}
