{{- if not .Values.credentials.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ddns-updater.fullname" . }}
  labels:
    {{- include "ddns-updater.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.credentials.usernameKey }}: {{ .Values.credentials.username | b64enc | quote }}
  {{ .Values.credentials.passwordKey }}: {{ .Values.credentials.password | b64enc | quote }}
{{- end }}
